### ISSUE TITLE
[Selenium] [Bug] Send Keys method in more challenging web

### ISSUE THREAD

**Issue by lstefaniszyn** [devonfw/mrchecker#166]
Contact person: Dacal Cantos, Jorge <jorge.dacal-cantos@capgemini.com>

If you remember, I told  you that sometimes, when we are doing tests using MrChecker, it fails because the string that we send as input in the form is not completely written.
For example, if our userName is “waiter”, sometimes it fails because it types “waitr”.

Code example:
WebElement userInput = getDriver().findElementDynamic(userLogin);
    userInput.sendKeys(userName);

Given situation was visible on Mai Tai Star application. For this, please contact also with @Zaneta Nawrot

**Comment by WroMaciej** [comment]
Actually I cannot repreduce the bug.
See my test of login form when user credentials are sent by `sendKeys()` method:
https://github.com/devonfw/devonfw-testing/blob/b9de4aaa1cbe91a7bfb456f14b7e1917552a133a/example/src/test/java/com/capgemini/mrchecker/selenium/projectY/FormAuthenticationTest.java#L122

I see 3 options:
1. sendKeys() method has been fixed
2. bug needs more attempts to exists (probability of bug issue would be less than 1%)
3. occurance of bug depends on frontend framework

Since I dont know project history, I cannot guess which option is correct.

**Comment by Jorge-Dacal** [comment]
The issue was testing My Thai Star. It is an Angular application, maybe depends on the frontend as you said or perhaps in the resources of the machine where the tests are executed.
