### ISSUE TITLE
Automate driver  download

### ISSUE THREAD

**Issue by magdalenaBartkowiakJowsa** [devonfw/mrchecker#178]

**Comment by Fab-Bit** [comment]
After investigation I checked that dependency that is responsible for driver download is outdated 
https://github.com/bonigarcia/webdrivermanager
Our: 2.2.0 Current 3.6.0
Start from 3.x there is implemented new mechanism that is responsible for checking in which version browser we have currently. And that driver will  be installed. I'm testing this locally.
Apart from that I also checked that TestSuites from path  [https://github.com/devonfw/devonfw-testing/blob/develop/example/src/test/java/com/capgemini/mrchecker/selenium/](url) are not working with specified browsers. On my  local env for every Suite, Chrome is started.

**Comment by Fab-Bit** [comment]
After investigation i check that there are two problems with selenium.
1. Chrome version is hardcoded in selenium grid http://10.40.234.103:4444/grid/console and this is old 64.0 ( firefox also ) According to https://github.com/bonigarcia/webdrivermanager/blob/master/src/main/resources/versions.properties
for chrome 64 webdriver should be 2.37.

 I hardcoded in DeviceManaher.java this ver to download but after run in jenkins it is visible 2.35 version http://10.40.234.40:8080/job/MrChecker-SDLC/job/CI_mrchecker-selenium-module/80/consoleFull.
**There is need to get access to Selenium Grid to check path were this downloaded driver is physically!** 

2. Problem is also connected with running tests in parallel and closing driver after one test. I run selenium for only one test and it's green http://10.40.234.40:8080/job/MrChecker-SDLC/job/CI_mrchecker-selenium-module/82/console. When I run all problem is with closing session beetwen one test and another. **There is need to verify if CloseDriver() method in DriverManager class is working fine.**

**Comment by Fab-Bit** [comment]
@gabrielstar

**Comment by MalgorzataDzienia** [comment]
Test cases issue with session exception (in my opinion problem 2) is solved in branch feature/selenium-testcases-bug​fix

**Comment by MalgorzataDzienia** [comment]
I developed fixes in branch feature/178_automate_driver_download

1. Selenium grid works as before - nothing changed. 
2. There was an issue with downloading drivers during local test execution in paralell mode. Driver was downloaded for every thread. This is fixed.
3. I implemented possibility to define version of driver in properties.file. If no version is defined, then the DriverManager decides what to download
4. beta versions of drivers are off and will not be downloaded
5. I didn't update version of Driver manager from Our: 2.0.0 Current 3.6.1. because it was not needed to implement this feature. I can do it if you wish. 

This feature is used for local test execution, so I cannot attach link to jenkins which shows how it works.
It was tested locally.
